<?php
include 'apidata/dataFetch.php';
include 'inc/header.php';
include 'inc/apiendpoint.php';
?>
<!--End header-->
<main class="main pages">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.php" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Pages <span></span> Terms-Conditions
            </div>
        </div>
    </div>
    <div class="page-content pt-50">
        <div class="container">
            <div class="row">
                <div class="col-xl-10 col-lg-12 m-auto">
                    <section class="row align-items-center mb-50">
                        <div class="col-lg-12">
                            <img src="assets/imgs/page/about-1.png" alt="" class="border-radius-15 mb-md-3 mb-lg-0 mb-sm-4" />
                        </div>
                        <div class="col-lg-12">
                            <div class="pl-25">
                                <h2 class="mb-30">Terms-Conditions</h2>
                                <h4 class="mb-30">A. Introduction:</h4>
                                <p class="mb-25">Welcome to Neo-Bazaar.com additionally thusly known as "we", "us" or " Neo Bazaar ". We are an online commercial center and these are the terms and conditions overseeing your entrance and utilization of Neo Bazaar alongside its related sub-areas, destinations, portable application, administrations and apparatuses (the "Website"). By utilizing the Site, you thusly acknowledge these terms and conditions (counting the connected data in this) and speak to that you consent to conform to these terms and conditions (the "Client Agreement"). This User Agreement is regarded as successful upon your utilization of the Site which means your acknowledgment of these terms. On the off chance that you don't consent to be bound by this User Agreement kindly don't get to, register with or utilize this Site. This Site is claimed and worked by Neo Bazaar Bangladesh Limited, an organization consolidated under the Companies Act, 1994.</p>
                                <p class="mb-20">The Site maintains whatever authority is needed to change, adjust, include, or expel bits of these Terms and Conditions whenever with no earlier warning. Changes will be successful when posted on the Site with no other notification gave. If it's not too much trouble check these Terms and Conditions normally for refreshes. You proceed with the utilization of the Site following the presenting of changes on Terms and Conditions of utilization establishes your acknowledgment of those changes.</p>
                                <h4 class="mb-30">B. CONDITIONS OF USE</h4>
                                <h6 class="mb-10">1. Your Account</h6>
                                <p class="mb-20">
                                    To get to specific administrations offered by the stage, we may necessitate that you make a record with us or give individual data to finish the making of a record. We may whenever in our sole and total watchfulness, nullify the username as well as password without giving any explanation or earlier notice and will not be at risk or answerable for any misfortunes endured by, brought about by, emerging out of, regarding or by reason of such solicitation or negation.</p>

                                <p class="mb-20"> Any agreement between us, regardless of whether for utilization of the site or in connection to the buy of items or administrations through the site will be represented by the laws of Bangladesh and all gatherings submit to the non-restrictive purview of the Bangladeshi Courts.
                                </p>
                                <p class="mb-20"> You are answerable for keeping up the classification of your client recognizable proof, password, account subtleties, and related private data. You consent to acknowledge this obligation and guarantee your record and its related subtleties are kept up safely consistently and every essential advance is taken to avoid abuse of your record. You ought to advise us promptly on the off chance that you have any motivation to accept that your secret phrase has gotten known to any other individual, or if the secret word is being, or is probably going to be, utilized in an unapproved way. You concur and recognize that any utilization of the Site and related administrations offered as well as any entrance to private data, information or interchanges utilizing your record and secret word will be esteemed to be either performed by you or approved by you all things considered. You consent to be bound by any entrance of the Site as well as utilization of any administrations offered by the Site (regardless of whether such access or use are approved by you or not). You concur that we will be entitled (yet not obliged) to follow up on, depend on or consider you exclusively capable and subject in regard thereof as though the equivalent were done or transmitted by you. You further concur and recognize that you will be bound by and consent to completely reimburse us against all misfortunes emerging from the utilization of or access to the Site through your record.
                                </p>

                                <p class="mb-20"> It would be ideal if you guarantee that the subtleties you give us are right and finish consistently. You are committed to refreshing insights regarding your record progressively by getting to your record on the web. For snippets of data you are not ready to refresh by getting to Your Account on the Site, you should advise us by means of our client care correspondence channels to help you with these changes. We claim all authority to decline access to the Site, end records, evacuate or alter content whenever without earlier notice to you. We may whenever in our sole and total carefulness, demand that you update your Personal Data or forthwith negate the record or related subtleties without giving any explanation or earlier notice and will not be at risk or liability for any misfortunes endured by or brought about by you or emerging out of or regarding or by reason of such solicitation or nullification. You thusly consent to change your secret key now and again and to keep your record secure and furthermore will be answerable for the privacy of your record and obligated for any revelation or use (regardless of whether such use is approved or not) of the username and additionally secret key..</p>
                                <h6 class="mb-10">2. Your account vs your order</h6>
                                <p class="mb-20">We Only Consider the name of an Neo Bazaar account holder as the owner of and the client of the product(s) which has been ordered from the respective Neo Bazaar account. You should not request for any changes in the name of the owner while delivering the product (i.e.: Motor Bike/Car, apartments, lands etc.)</p>

                                <p class="mb-20">Neo Bazaar retains all kinds of authority to ban/cancel/freeze/unfreeze your account(s) if they think it should be done so. Neo Bazaar is not bound to provide the balance amount (of cash back) to you if your account is blocked/banned. Any kind of balance paid by you through bkash/bank/cash would be refunded to you within a reasonable time period. Please note that it may depend on the calculation of your total payment vs the cashback you received and used..</p>
                                <h6 class="mb-10">3. Your Conduct:</h6>
                                <p class="mb-20">You should not utilize the site at all that causes, or is probably going to cause, the Site or access to it to interfere, harmed or disabled in any capacity. You should not participate in exercises that could hurt or conceivably hurt the Site, its workers, officials, delegates, partners or some other gathering legitimately or in a roundabout way connected with the Site or access to it to be intruded, harmed or debilitated in any capacity. You comprehend that you, and not us, are answerable for every single electronic correspondence and substance sent from your PC to us and you should utilize the Site for legal purposes as it were. You are carefully restricted from utilizing the Site.</p>

                                <p class="mb-20"> Neo Bazaar might not be subject to any individual for any misfortune or harm, which may emerge from the utilization of any of the data contained in any of the materials on this site.</p>

                                <p class="mb-20">
                                    for deceitful purposes, or regarding a criminal offense or other unlawful movements to send, utilize or reuse any material that doesn't have a place with you; or is illicit, hostile (counting yet not constrained to material that is explicitly unequivocal substance or which advances prejudice, dogmatism, scorn or physical mischief), tricky, misdirecting, damaging, foul, hassling, disrespectful, abusive, derogatory, vulgar, obscene, pedophilic or threatening; ethically questionable, stigmatizing or in break of copyright, trademark, secrecy, protection or some other exclusive data or right; or is generally damaging to outsiders; or identifies with or advances tax evasion or betting; or is unsafe to minors in any capacity; or mimics someone else; or undermines the solidarity, trustworthiness, security or power of Bangladesh or neighborly relations with remote States; or offensive or generally unlawful in any way at all; or which comprises of or contains programming infections, political battling, business sales, networking letters, mass mailings or any ‘spam‘ Use the Site for illicit purposes. to cause irritation, bother or unnecessary nervousness for whatever other purposes that is other than what is expected by us</p>
                                <h6 class="mb-10">4. Submission:</h6>
                                <p class="mb-20">Anything that you submit to the Site or potentially give to us, including yet not restricted to, questions, audits, remarks, and proposals (on the whole, "Entries") will turn into our sole and selective property and will not become back to you. Notwithstanding the rights pertinent to any Submission, when you present remarks or surveys on the Site, you additionally award us the privilege to utilize the name that you submit, regarding such audit, remark, or other substance. You will not utilize a bogus email address, profess to be somebody other than yourself or generally misdirect us or outsiders with regards to the cause of any Submissions. We may, yet will not be committed to, expel or alter any Submissions with no notification or lawful course appropriate to us in such manner.</p>
                                <h6 class="mb-10">5. CLAIMS AGAINST OBJECTIONABLE CONTENT:</h6>
                                <p class="mb-20">We list a huge number of items including apartments & Lands available to be purchased offered by various dealers on the Site and host different remarks on postings, it isn't workable for us to know about the substance of every item recorded available to be purchased or each remark or survey that is shown. Appropriately, we work on a "guarantee, audit and takedown" premise. On the off chance that you accept that any substance on the Site is illicit, hostile (counting yet not restricted to material that is explicitly express substance or which advances prejudice, bias, scorn or physical mischief), beguiling, deluding, harsh, profane, irritating, impious, slanderous, offensive, revolting, obscene, pedophilic or threatening; ethnically questionable, criticizing; or is generally damaging to outsiders; or identifies with or advances tax evasion or betting; or is destructive to minors in any capacity; or mimics someone else; or compromises the solidarity, trustworthiness, security or sway of Bangladesh or cordial relations with remote States; or shocking or generally unlawful in any way at all; or which comprises of or contains programming infections, (" frightful substance "), please tell us quickly by following by keeping in touch with us on legal@ Neo-Bazaar.com We will make every single useful undertaking to examine and evacuate substantial offensive substance griped about inside a sensible measure of time.</p>
                                <p class="mb-20">If it's not too much trouble guarantee to give your name, address, contact data and the same number of pertinent subtleties of the case including the name of frightful substance party, occasions of protest, confirmation of complaint among others. If you don't mind note that giving inadequate subtleties will ruin your case and unusable for legitimate purposes</p>
                                <h6 class="mb-10">6. CLAIMS AGAINST INFRINGING CONTENT:</h6>
                                <p class="mb-20">We regard the licensed innovation of others. On the off chance that you accept that your licensed innovation rights have been utilized such that offers to ascend to worries of encroachment if it's not too much trouble illuminate us and we will endeavor every single sensible exertion to address your worry inside a sensible measure of time. It would be ideal if you guarantee to give your name, address, contact data and the same number of pertinent subtleties of the case including the name of encroaching gathering, cases of encroachment, and verification of encroachment among others. If you don't mind note that giving deficient subtleties will ruin your case and unusable for lawful purposes. What's more, giving bogus or misdirecting data might be viewed as a legitimate offense and might be trailed by lawful procedures.</p>
                                <p class="mb-20">We likewise regard a maker's entitlement to go into selective appropriation or resale understandings for its items. In any case, infringement of such understandings doesn’t establish licensed innovation rights encroachment. As the implementation of these understandings is an issue between the producer, wholesaler and additionally particular affiliate, it would not be befitting for us to aid the authorization of such exercises. While we can't give legitimate guidance, nor share private data as secured by the law, we suggest that any inquiries or concerns with respect to your privileges might be steered to lawful authority.</p>
                                <h6 class="mb-10">7. Indemnity:</h6>
                                <p class="mb-20">You will repay and hold innocuous Neo Bazaar Limited, its auxiliaries, offshoots, and their particular officials, executives, operators, and representatives, from any case or request, or activities including sensible lawyer's expenses, made by any outsider or punishment forced due to or emerging out of your break of these Terms and Conditions or any record joined by reference, or your infringement of any law, rules, guidelines or the privileges of an outsider.</p>
                                <p class="mb-20">You therefore explicitly discharge Neo Bazaar as possessed by offshoots as well as any of its officials and delegates from any cost, harm, obligation or other outcome of any of the activities/inactions of the merchants or other specialist co-ops and explicitly waiver any cases or requests that you may have for this benefit under any resolution, contract or something else.</p>
                                <h6 class="mb-10">8. Losses:</h6>
                                <p class="mb-20">We won't be answerable for any business or individual misfortunes (counting however not restricted to loss of benefits, income, contracts, foreseen investment funds, information, altruism, or squandered consumption) or whatever other backhanded or weighty misfortune that isn't sensibly predictable to both you and us when you initiated utilizing the Site.</p>
                                <h6 class="mb-10">9. Corrections TO CONDITIONS OR ALTERATIONS OF SERVICE AND RELATED PROMISE</h6>
                                <p class="mb-20">We maintain all authority to make changes to the Site, its strategies, these terms and conditions and some other freely showed condition or administration guarantee whenever. You will be dependent upon the approaches and terms and conditions in power at the time you utilized the Site except if any change to those strategies or these conditions is required to be made by law or government expert (in which case it will apply to orders recently set by you). In the event that any of these conditions is regarded invalid, void, or in any way, shape or form unenforceable, that condition will be considered severable and won't influence the legitimacy and enforceability of any outstanding condition.</p>
                                <h6 class="mb-10">10. WAIVER</h6>
                                <p class="mb-20">You recognize and perceive that we are a private business endeavor and claim all authority to lead the business to accomplish our targets in a way we esteem fit. You additionally recognize that in the event that you break the conditions expressed on our Site and we make no move, we are as yet qualified for utilizing our privileges and cures in whatever other circumstance where you rupture these conditions.</p>
                                <div class="carausel-3-columns-cover position-relative">
                                    <div id="carausel-3-columns-arrows"></div>
                                    <div class="carausel-3-columns" id="carausel-3-columns">
                                        <img src="assets/imgs/page/about-2.png" alt="" />
                                        <img src="assets/imgs/page/about-3.png" alt="" />
                                        <img src="assets/imgs/page/about-4.png" alt="" />
                                        <img src="assets/imgs/page/about-2.png" alt="" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</main>
<?php
include 'inc/footer.php';
?>